// ARC 4: ASHFALL CAVERNS — Floors 31–40
import type { ArcData } from './types';
const arc4: ArcData = {
  arc: 4, name: "Ashfall Caverns", theme: "fire",
  entryNarration: "*The heat presses against your skin like a warning. Below, something burns — not with fire but with something older than fire.*",
  floorNarrations: {
    31: "*The cavern floor is warm beneath your feet. Something down here has been burning for a long time.*",
    32: "*The temperature climbs. The air smells of sulfur and old ash.*",
    33: "*The lava rivers begin here. Narrow at first. You can step over them. For now.*",
    34: "*The ash is ankle deep. Every step disturbs it. The ash is still warm.*",
    35: "*Halfway through the Caverns. Your equipment is hot to the touch.*",
    36: "*The lava rivers are wider here. One of them moves. Lava shouldn't move like that.*",
    37: "*A chamber full of bones — creatures that came here and couldn't leave.*",
    38: "*The ceiling is low and dripping. Not water. Don't let it touch you.*",
    39: "*A natural tunnel bored through solid rock by something enormous. Teeth marks on the smooth walls.*",
    40: "*The deepest chamber. At the center — something that has been burning since before the tower existed.*",
  },
  mobs: {
    31: { id: "ember_golem", name: "Ember Golem", emoji: "🔥", maxHp: 540, maxMp: 60, attack: 64, defense: 24, speed: 14, isBoss: false,
      lore: "*A living furnace. It doesn't burn with malice. It just burns.*",
      moves: [
        { name: "Magma Fist",   emoji: "🌋", damage: 64, mpCost: 0,  weight: 4 },
        { name: "Ash Cloud",    emoji: "🌫️", damage: 36, mpCost: 25, weight: 3, effect: { kind: "slow", value: 22, duration: 3 } },
        { name: "Inferno Core", emoji: "🔥", damage: 52, mpCost: 35, weight: 2, effect: { kind: "burn", value: 28, duration: 4 } },
      ],
    },
    32: { id: "fire_wraith", name: "Fire Wraith", emoji: "🌪️", maxHp: 460, maxMp: 100, attack: 60, defense: 9, speed: 48, isBoss: false,
      lore: "*Someone burned to death with enough rage to keep moving.*",
      moves: [
        { name: "Flame Touch", emoji: "🔥", damage: 52, mpCost: 20, weight: 4, effect: { kind: "burn", value: 22, duration: 3 } },
        { name: "Wildfire",    emoji: "💥", damage: 68, mpCost: 40, weight: 2 },
        { name: "Smolder",     emoji: "💨", damage: 32, mpCost: 25, weight: 3, effect: { kind: "burn", value: 14, duration: 6 } },
      ],
    },
    33: { id: "lava_crawler", name: "Lava Crawler", emoji: "🦎", maxHp: 580, maxMp: 40, attack: 66, defense: 20, speed: 26, isBoss: false,
      lore: "*Lives in the lava rivers. You cannot tell where the creature ends and the lava begins.*",
      moves: [
        { name: "Lava Surge",   emoji: "🌋", damage: 66, mpCost: 0,  weight: 4 },
        { name: "Scorch Trail", emoji: "🔴", damage: 48, mpCost: 20, weight: 3, effect: { kind: "burn", value: 20, duration: 5 } },
        { name: "Submerge",     emoji: "🌊", damage: 0,  mpCost: 30, weight: 2, effect: { kind: "regen", value: 38, duration: 2 } },
      ],
    },
    34: { id: "ash_revenant", name: "Ash Revenant", emoji: "💀", maxHp: 520, maxMp: 70, attack: 62, defense: 14, speed: 36, isBoss: false,
      lore: "*The spirit of something that burned completely and became the ash itself.*",
      moves: [
        { name: "Ash Surge",    emoji: "💨", damage: 62, mpCost: 25, weight: 3, effect: { kind: "slow", value: 24, duration: 3 } },
        { name: "Ember Rain",   emoji: "🔥", damage: 50, mpCost: 20, weight: 3, effect: { kind: "burn", value: 18, duration: 4 } },
        { name: "Reconstruct",  emoji: "🌀", damage: 0,  mpCost: 35, weight: 2, effect: { kind: "regen", value: 35, duration: 2 } },
      ],
    },
    35: { id: "heat_stalker", name: "Heat Stalker", emoji: "👁️", maxHp: 560, maxMp: 80, attack: 68, defense: 16, speed: 42, isBoss: false,
      lore: "*Invisible in the heat haze. You only know it's there when it's already close.*",
      moves: [
        { name: "Heat Strike",   emoji: "💥", damage: 68, mpCost: 0,  weight: 4 },
        { name: "Thermal Pulse", emoji: "🌡️", damage: 50, mpCost: 30, weight: 3, effect: { kind: "burn", value: 25, duration: 4 } },
        { name: "Haze Fade",     emoji: "💨", damage: 0,  mpCost: 25, weight: 2, effect: { kind: "slow", value: 20, duration: 2 } },
      ],
    },
    36: { id: "magma_serpent", name: "Magma Serpent", emoji: "🐍", maxHp: 620, maxMp: 60, attack: 70, defense: 22, speed: 30, isBoss: false,
      lore: "*The lava rivers move because of it.*",
      moves: [
        { name: "Magma Bite",  emoji: "🐍", damage: 70, mpCost: 0,  weight: 4 },
        { name: "River Surge", emoji: "🌋", damage: 58, mpCost: 25, weight: 3, effect: { kind: "burn", value: 30, duration: 4 } },
        { name: "Coil",        emoji: "🌀", damage: 42, mpCost: 20, weight: 2, effect: { kind: "stun", value: 0, duration: 1 } },
      ],
    },
    37: { id: "bone_pyromancer", name: "Bone Pyromancer", emoji: "💀", maxHp: 580, maxMp: 120, attack: 64, defense: 12, speed: 28, isBoss: false,
      lore: "*A sorcerer who came here to study the fire. The fire studied them back.*",
      moves: [
        { name: "Fireball",    emoji: "🔥", damage: 64, mpCost: 30, weight: 3, effect: { kind: "burn", value: 22, duration: 3 } },
        { name: "Fire Storm",  emoji: "🌪️", damage: 78, mpCost: 50, weight: 2 },
        { name: "Bone Ward",   emoji: "🛡️", damage: 0,  mpCost: 35, weight: 2, effect: { kind: "regen", value: 40, duration: 3 } },
        { name: "Incinerate",  emoji: "💥", damage: 90, mpCost: 60, weight: 1, effect: { kind: "burn", value: 35, duration: 5 } },
      ],
    },
    38: { id: "drip_horror", name: "Ceiling Drip", emoji: "🌋", maxHp: 600, maxMp: 50, attack: 72, defense: 18, speed: 22, isBoss: false,
      lore: "*It lives in the ceiling. It drops when something warm walks beneath it.*",
      moves: [
        { name: "Drop Strike",  emoji: "⬇️", damage: 72, mpCost: 0,  weight: 4 },
        { name: "Splatter",     emoji: "🌋", damage: 55, mpCost: 20, weight: 3, effect: { kind: "burn", value: 28, duration: 4 } },
        { name: "Ceiling Pull", emoji: "🔝", damage: 0,  mpCost: 30, weight: 2, effect: { kind: "regen", value: 42, duration: 2 } },
      ],
    },
    39: { id: "ancient_fire_beast", name: "Ancient Fire Beast", emoji: "🦁", maxHp: 680, maxMp: 80, attack: 76, defense: 26, speed: 32, isBoss: false,
      lore: "*The original predator of this cavern. The teeth marks in the walls are its.*",
      moves: [
        { name: "Ancient Roar", emoji: "📣", damage: 40, mpCost: 0,  weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Fire Maw",     emoji: "🦁", damage: 76, mpCost: 30, weight: 3, effect: { kind: "burn", value: 32, duration: 4 } },
        { name: "Primal Smash", emoji: "💥", damage: 90, mpCost: 0,  weight: 2 },
        { name: "Territorial",  emoji: "🛡️", damage: 0,  mpCost: 40, weight: 2, effect: { kind: "regen", value: 48, duration: 3 } },
      ],
    },
  },
  boss: {
    id: "ignis_the_consuming", name: "Ignis, the Consuming", emoji: "🌋",
    maxHp: 3600, maxMp: 550, attack: 122, defense: 36, speed: 40, isBoss: true,
    lore: "*It is simply waiting for something worthy of its fire.*",
    entranceMonologue: [
      `🌋 *Something rises from the rock. Not a creature. A presence that happens to have a form.*`,
      `🌋 **Ignis:** *"You smell like ambition."*`,
      `🌋 **Ignis:** *"I have consumed ambition before. It barely warmed me."*`,
      `🌋 **Ignis:** *"Show me you're different. Or be ash."*`,
    ],
    deathMonologue: `🌋 **Ignis:** *"...Warm."*\n🌋 **Ignis:** *"You were actually... warm."*\n🌋 **Ignis:** *"The caverns are yours."*`,
    playerKillTaunt: `🌋 **Ignis:** *"You were... not different."*\n🌋 **Ignis:** *"Pity."*`,
    reactToHeavyHit: [
      `🌋 **Ignis:** *"...You found something. Good. That's what I came here for."*`,
      `🌋 **Ignis:** *"I haven't felt that in centuries. Again."*`,
    ],
    reactToLightHit: [
      `🌋 **Ignis:** *"That is not fire. That is a candle."*`,
      `🌋 **Ignis:** *"Commit."*`,
    ],
    reactToHeal: [`🌋 **Ignis:** *"I have burned since before your civilization existed."*`],
    reactToPlayerLow: [`🌋 **Ignis:** *"Low. But not out. Keep going."*`],
    reactToBossLow: [
      `🌋 **Ignis:** *"...You're actually doing it."*`,
      `🌋 **Ignis:** *"You are different."*\n🌋 **Ignis:** *"Now finish it."*`,
    ],
    midBattleThoughts: [
      `🌋 **Ignis:** *"Fight harder. I want to feel something."*`,
      `🌋 **Ignis:** *"Stop dodging. Face me properly."*`,
    ],
    enrageLines: [
      `🌋 *The entire cavern ignites.*`,
      `🌋 **Ignis — ENRAGED:** *"CONSUME. CONSUME. CONSUME."*`,
    ],
    enrageAt: 28,
    moves: [
      { name: "Eruption",     emoji: "🌋", damage: 116, mpCost: 0,  weight: 3, taunt: `🌋 **Ignis:** *"Eruption."*` },
      { name: "Lava River",   emoji: "🔴", damage: 92,  mpCost: 40, weight: 3, effect: { kind: "burn", value: 36, duration: 4 }, taunt: `🌋 **Ignis:** *"Lava River."*` },
      { name: "Cinder Storm", emoji: "🌪️", damage: 68,  mpCost: 50, weight: 2, effect: { kind: "slow", value: 28, duration: 3 }, taunt: `🌋 **Ignis:** *"Cinder Storm."*` },
      { name: "Magma Shield", emoji: "🛡️", damage: 0,   mpCost: 45, weight: 2, effect: { kind: "regen", value: 82, duration: 3 }, taunt: `🌋 **Ignis:** *"Magma Shield."*` },
      { name: "Core Blast",   emoji: "💥", damage: 148, mpCost: 70, weight: 1, taunt: `🌋 **Ignis:** *"Core Blast."*` },
    ],
    enrageMoves: [
      { name: "CONSUMING FLAME", emoji: "🔥", damage: 220, mpCost: 0,  weight: 3, taunt: `🌋 **Ignis — ENRAGED:** *"CONSUMING FLAME."*` },
      { name: "Apocalypse Fire", emoji: "☄️", damage: 172, mpCost: 75, weight: 3, effect: { kind: "burn", value: 55, duration: 5 }, taunt: `🌋 **Ignis — ENRAGED:** *"Apocalypse Fire."*` },
      { name: "Rebirth Flame",   emoji: "🔁", damage: 50,  mpCost: 60, weight: 2, effect: { kind: "regen", value: 100, duration: 3 }, taunt: `🌋 **Ignis — ENRAGED:** *"Rebirth Flame."*` },
    ],
  },
};
export default arc4;
