// ARC 5: THE VOID BETWEEN — Floors 41–50
import type { ArcData } from './types';
const arc5: ArcData = {
  arc: 5, name: "The Void Between", theme: "void",
  entryNarration: "*Not dark — the concept of dark requires light to oppose. This is the absence of both. Your footsteps make no sound.*",
  floorNarrations: {
    41: "*The first floor of the void. You can see the ground beneath your feet but nothing else.*",
    42: "*Something passes through you. Not around. Through.*",
    43: "*The void speaks, briefly. The feeling is: you shouldn't be here.*",
    44: "*Time feels different here. Minutes or hours. You cannot tell.*",
    45: "*Halfway through the void. You stop checking if you're still breathing and start trusting that you are.*",
    46: "*Something enormous in the distance. It hasn't noticed you. You don't move.*",
    47: "*The void begins to have texture. The air has resistance. Like something is pressing back.*",
    48: "*Your shadow detaches from you. It continues walking ahead.*",
    49: "*The void narrows here — not physically, but in feeling.*",
    50: "*The center of the void. You feel something looking at you. You look back. There is nothing. The nothing looks back.*",
  },
  mobs: {
    41: { id: "void_phantom", name: "Void Phantom", emoji: "🌑", maxHp: 620, maxMp: 120, attack: 74, defense: 14, speed: 54, isBoss: false,
      lore: "*Exists between moments. When it attacks, it attacks from a time that hasn't happened yet.*",
      moves: [
        { name: "Temporal Strike", emoji: "⏱️", damage: 74, mpCost: 25, weight: 3 },
        { name: "Void Drain",      emoji: "🌀", damage: 48, mpCost: 35, weight: 3, effect: { kind: "mp_drain", value: 55, duration: 1 } },
        { name: "Phase Tear",      emoji: "💥", damage: 90, mpCost: 50, weight: 2, effect: { kind: "bleed", value: 28, duration: 3 } },
      ],
    },
    42: { id: "silence_walker", name: "Silence Walker", emoji: "🤫", maxHp: 580, maxMp: 100, attack: 70, defense: 16, speed: 42, isBoss: false,
      lore: "*There is no sound when it moves. There is no sound when you scream.*",
      moves: [
        { name: "Silent Strike",  emoji: "💨", damage: 70, mpCost: 0,  weight: 4 },
        { name: "Void Whisper",   emoji: "🤫", damage: 42, mpCost: 30, weight: 3, effect: { kind: "silence", value: 0, duration: 2 } },
        { name: "Consumption",    emoji: "🕳️", damage: 58, mpCost: 40, weight: 2, effect: { kind: "mp_drain", value: 48, duration: 1 } },
      ],
    },
    43: { id: "absence", name: "The Absence", emoji: "⬜", maxHp: 640, maxMp: 80, attack: 76, defense: 10, speed: 50, isBoss: false,
      lore: "*The void made self-aware, briefly. It is confused. It is also hostile.*",
      moves: [
        { name: "Erase",          emoji: "⬜", damage: 76, mpCost: 0,  weight: 4 },
        { name: "Absence Touch",  emoji: "🤚", damage: 60, mpCost: 30, weight: 3, effect: { kind: "slow", value: 26, duration: 3 } },
        { name: "Unfocus",        emoji: "💨", damage: 0,  mpCost: 35, weight: 2, effect: { kind: "regen", value: 45, duration: 2 } },
      ],
    },
    44: { id: "time_fragment", name: "Time Fragment", emoji: "⏳", maxHp: 660, maxMp: 110, attack: 78, defense: 18, speed: 38, isBoss: false,
      lore: "*A piece of time that got lost in the void.*",
      moves: [
        { name: "Temporal Crush", emoji: "⏳", damage: 78, mpCost: 30, weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Age",            emoji: "👴", damage: 55, mpCost: 40, weight: 3, effect: { kind: "slow", value: 30, duration: 4 } },
        { name: "Regress",        emoji: "🔁", damage: 0,  mpCost: 35, weight: 2, effect: { kind: "regen", value: 50, duration: 3 } },
      ],
    },
    45: { id: "void_predator", name: "Void Predator", emoji: "🦅", maxHp: 700, maxMp: 90, attack: 82, defense: 20, speed: 58, isBoss: false,
      lore: "*Evolved to hunt in the void. In the void, existence is loud.*",
      moves: [
        { name: "Void Dive",       emoji: "🦅", damage: 82, mpCost: 0,  weight: 4 },
        { name: "Existence Drain", emoji: "🌑", damage: 60, mpCost: 35, weight: 3, effect: { kind: "mp_drain", value: 60, duration: 1 } },
        { name: "Vacuum",          emoji: "💨", damage: 45, mpCost: 30, weight: 2, effect: { kind: "slow", value: 32, duration: 3 } },
      ],
    },
    46: { id: "slow_enormous", name: "The Slow Enormous", emoji: "🐘", maxHp: 900, maxMp: 50, attack: 88, defense: 30, speed: 8, isBoss: false,
      lore: "*You saw it from a distance. It noticed you when you noticed it.*",
      moves: [
        { name: "Enormous Step", emoji: "👣", damage: 88, mpCost: 0,  weight: 3 },
        { name: "Void Weight",   emoji: "⬇️", damage: 72, mpCost: 0,  weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Presence",      emoji: "📡", damage: 50, mpCost: 30, weight: 2, effect: { kind: "slow", value: 35, duration: 4 } },
        { name: "Absorb Void",   emoji: "🌑", damage: 0,  mpCost: 40, weight: 2, effect: { kind: "regen", value: 55, duration: 3 } },
      ],
    },
    47: { id: "pressure_shade", name: "Pressure Shade", emoji: "🌫️", maxHp: 720, maxMp: 130, attack: 80, defense: 16, speed: 44, isBoss: false,
      lore: "*The resistance you felt in the air. Given form.*",
      moves: [
        { name: "Pressure Wave", emoji: "💥", damage: 80, mpCost: 30, weight: 3 },
        { name: "Compress",      emoji: "🗜️", damage: 65, mpCost: 40, weight: 3, effect: { kind: "slow", value: 28, duration: 3 } },
        { name: "Disperse",      emoji: "💨", damage: 0,  mpCost: 30, weight: 2, effect: { kind: "regen", value: 48, duration: 2 } },
      ],
    },
    48: { id: "shadow_self", name: "Shadow Self", emoji: "🌑", maxHp: 760, maxMp: 120, attack: 86, defense: 22, speed: 40, isBoss: false,
      lore: "*Your shadow, detached. It has opinions about the direction you've been going.*",
      moves: [
        { name: "Shadow Punch", emoji: "👊", damage: 86, mpCost: 0,  weight: 4 },
        { name: "Detach",       emoji: "💨", damage: 60, mpCost: 30, weight: 3, effect: { kind: "bleed", value: 30, duration: 3 } },
        { name: "Dark Mirror",  emoji: "🪞", damage: 70, mpCost: 40, weight: 2, effect: { kind: "stun", value: 0, duration: 1 } },
      ],
    },
    49: { id: "void_herald", name: "Void Herald", emoji: "📯", maxHp: 820, maxMp: 150, attack: 90, defense: 24, speed: 35, isBoss: false,
      lore: "*Sent ahead of the Nothing.*",
      moves: [
        { name: "Herald's Blow",   emoji: "📯", damage: 90,  mpCost: 0,  weight: 3 },
        { name: "Void Call",       emoji: "🌑", damage: 65,  mpCost: 50, weight: 3, effect: { kind: "silence", value: 0, duration: 3 } },
        { name: "Announcement",    emoji: "💥", damage: 110, mpCost: 60, weight: 2, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Presence Buffer", emoji: "🛡️", damage: 0,   mpCost: 45, weight: 2, effect: { kind: "regen", value: 60, duration: 3 } },
      ],
    },
  },
  boss: {
    id: "the_nothing", name: "The Nothing", emoji: "⬛",
    maxHp: 4200, maxMp: 600, attack: 138, defense: 42, speed: 48, isBoss: true,
    lore: "*It is the space between spaces. The gap between moments. It was here before the tower and will be here after.*",
    entranceMonologue: [
      `⬛ *The lights go out. Not darkness — the absence of the concept.*`,
      `⬛ **The Nothing:** *"You came to the void."*`,
      `⬛ **The Nothing:** *"What did you expect to find here?"*`,
      `⬛ *You feel it looking at you the way you look at something you want.*`,
      `⬛ **The Nothing:** *"You contain something."*`,
      `⬛ **The Nothing:** *"I want it."*`,
    ],
    deathMonologue: `⬛ *Slowly — sounds return. Light, at the edges.*\n⬛ **The Nothing:** *"...Something."*\n⬛ **The Nothing:** *"You are something."*`,
    playerKillTaunt: `⬛ **The Nothing:** *"Nothing."*`,
    reactToHeavyHit: [
      `⬛ **The Nothing:** *"...You can damage nothing. Interesting."*`,
    ],
    reactToLightHit: [`⬛ **The Nothing:** *"Less."*`],
    reactToHeal: [`⬛ **The Nothing:** *"Nothing cannot be destroyed. Only redistributed."*`],
    reactToPlayerLow: [`⬛ **The Nothing:** *"Low. Soon — nothing."*`],
    reactToBossLow: [
      `⬛ *The void trembles.*\n⬛ **The Nothing:** *"...What are you?"*`,
    ],
    midBattleThoughts: [
      `⬛ **The Nothing:** *"..."*`,
      `⬛ **The Nothing:** *"You persist."*`,
      `⬛ **The Nothing:** *"Everything that enters the void stops. You have not stopped."*`,
    ],
    enrageLines: [
      `⬛ **The Nothing:** *"YOU WILL BECOME NOTHING."*`,
      `⬛ **The Nothing — ENRAGED:** *"I AM THE END OF ALL THINGS. ACCEPT IT."*`,
    ],
    enrageAt: 22,
    moves: [
      { name: "Erase",          emoji: "⬛", damage: 132, mpCost: 0,  weight: 3, taunt: `⬛ **The Nothing:** *"Erase."*` },
      { name: "Void Pull",      emoji: "🕳️", damage: 98,  mpCost: 45, weight: 3, effect: { kind: "mp_drain", value: 72, duration: 1 }, taunt: `⬛ **The Nothing:** *"Void Pull."*` },
      { name: "Silence All",    emoji: "🤫", damage: 62,  mpCost: 55, weight: 2, effect: { kind: "silence", value: 0, duration: 3 }, taunt: `⬛ **The Nothing:** *"Silence All."*` },
      { name: "Oblivion Touch", emoji: "💀", damage: 170, mpCost: 80, weight: 1, taunt: `⬛ **The Nothing:** *"Oblivion Touch."*` },
      { name: "Void Regen",     emoji: "🔁", damage: 0,   mpCost: 60, weight: 2, effect: { kind: "regen", value: 110, duration: 3 }, taunt: `⬛ **The Nothing:** *"Void Regen."*` },
    ],
    enrageMoves: [
      { name: "ABSOLUTE VOID",  emoji: "🌌", damage: 245, mpCost: 0,  weight: 3, taunt: `⬛ **The Nothing — ENRAGED:** *"ABSOLUTE VOID. NOTHING REMAINS."*` },
      { name: "Reality Erase",  emoji: "⬛", damage: 196, mpCost: 90, weight: 3, effect: { kind: "silence", value: 0, duration: 4 }, taunt: `⬛ **The Nothing — ENRAGED:** *"Reality Erase."*` },
      { name: "Consume All",    emoji: "🕳️", damage: 148, mpCost: 75, weight: 2, effect: { kind: "mp_drain", value: 95, duration: 1 }, taunt: `⬛ **The Nothing — ENRAGED:** *"Consume All."*` },
    ],
  },
};
export default arc5;
