// ARC 6: DOMINION OF SHADOWS — Floors 51–60
import type { ArcData } from './types';
const arc6: ArcData = {
  arc: 6, name: "Dominion of Shadows", theme: "shadow",
  entryNarration: "*Your shadow detaches from you the moment you enter and walks ahead. You follow it.*",
  floorNarrations: {
    51: "*Everything has a shadow and the shadows are wrong — too long, the wrong shape, pointing the wrong direction.*",
    52: "*The shadows move when nothing else does.*",
    53: "*A hall of captured shadows — pinned to the wall with dark needles. Some still struggling.*",
    54: "*Your shadow returns briefly, tugs at your ankle, then leaves again.*",
    55: "*The light sources here cast no light. They cast dark.*",
    56: "*The shadows are in conversation. They stop when you enter.*",
    57: "*The floor is mirrored. Your shadow below is not matching your movement.*",
    58: "*Trophies — armor, weapons. All belong to warriors who came before. All still have their shadows attached.*",
    59: "*Your shadow stops at the door. Turns to face you. Looks at you. Then steps aside.*",
    60: "*The shadow throne room. One figure, sitting casually, looking at you as though he's been waiting.*",
  },
  mobs: {
    1: { id: "shadow_reaper", name: "Shadow Reaper", emoji: "🌑", maxHp: 740, maxMp: 150, attack: 90, defense: 22, speed: 58, isBoss: false,
      lore: "*A reaper made not of death but of the absence of light.*",
      moves: [
        { name: "Reap",            emoji: "⚔️", damage: 90, mpCost: 0,  weight: 4 },
        { name: "Shadow Drain",    emoji: "🌑", damage: 58, mpCost: 35, weight: 3, effect: { kind: "mp_drain", value: 62, duration: 1 } },
        { name: "Darkness Shroud", emoji: "🌫️", damage: 44, mpCost: 40, weight: 2, effect: { kind: "slow", value: 28, duration: 3 } },
      ],
    },
    2: { id: "shadow_hunter", name: "Shadow Hunter", emoji: "🏹", maxHp: 700, maxMp: 120, attack: 88, defense: 14, speed: 65, isBoss: false,
      lore: "*Hunts by tracking shadows. Your shadow is already known to it.*",
      moves: [
        { name: "Shadow Arrow",  emoji: "🏹", damage: 88, mpCost: 0,  weight: 4 },
        { name: "Dark Pinpoint", emoji: "🎯", damage: 72, mpCost: 25, weight: 3, effect: { kind: "bleed", value: 32, duration: 4 } },
        { name: "Fade",          emoji: "💨", damage: 0,  mpCost: 30, weight: 2, effect: { kind: "regen", value: 52, duration: 2 } },
      ],
    },
    3: { id: "pinned_shadow", name: "Escaped Pinned Shadow", emoji: "⬛", maxHp: 720, maxMp: 90, attack: 86, defense: 18, speed: 48, isBoss: false,
      lore: "*One of the shadows from the hall escaped its pin. It is extremely angry.*",
      moves: [
        { name: "Pin Strike",   emoji: "📌", damage: 86, mpCost: 0,  weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Shadow Lash",  emoji: "⬛", damage: 70, mpCost: 20, weight: 3, effect: { kind: "bleed", value: 25, duration: 4 } },
        { name: "Darken",       emoji: "🌑", damage: 55, mpCost: 35, weight: 2, effect: { kind: "slow", value: 30, duration: 3 } },
      ],
    },
    4: { id: "dark_sovereign_lesser", name: "Dark Sovereign", emoji: "👑", maxHp: 820, maxMp: 130, attack: 96, defense: 28, speed: 42, isBoss: false,
      lore: "*A minor king of the shadow realm. MINOR by shadow standards.*",
      moves: [
        { name: "Sovereign Strike", emoji: "👑", damage: 96, mpCost: 0,  weight: 3 },
        { name: "Dark Decree",      emoji: "📜", damage: 68, mpCost: 50, weight: 3, effect: { kind: "silence", value: 0, duration: 2 } },
        { name: "Shadow Throne",    emoji: "🪑", damage: 0,  mpCost: 45, weight: 2, effect: { kind: "regen", value: 65, duration: 3 } },
      ],
    },
    5: { id: "wrong_light", name: "Wrong Light", emoji: "💡", maxHp: 760, maxMp: 110, attack: 92, defense: 20, speed: 52, isBoss: false,
      lore: "*A light source that casts dark. It has become sentient.*",
      moves: [
        { name: "Dark Beam",  emoji: "💡", damage: 92, mpCost: 25, weight: 4 },
        { name: "Wrong Cast", emoji: "🌑", damage: 72, mpCost: 35, weight: 3, effect: { kind: "slow", value: 32, duration: 3 } },
        { name: "Invert",     emoji: "🔄", damage: 55, mpCost: 40, weight: 2, effect: { kind: "silence", value: 0, duration: 2 } },
      ],
    },
    6: { id: "shadow_conversant", name: "Shadow Conversant", emoji: "🗣️", maxHp: 800, maxMp: 160, attack: 94, defense: 24, speed: 40, isBoss: false,
      lore: "*You interrupted something important. It is taking this personally.*",
      moves: [
        { name: "Dark Words",      emoji: "🗣️", damage: 94, mpCost: 30, weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Shadow Rhetoric", emoji: "💬", damage: 75, mpCost: 45, weight: 3, effect: { kind: "slow", value: 25, duration: 3 } },
        { name: "Shadow Commune",  emoji: "🌑", damage: 0,  mpCost: 55, weight: 2, effect: { kind: "regen", value: 70, duration: 3 } },
      ],
    },
    7: { id: "mirror_floor_shade", name: "Mirror Floor Shade", emoji: "🪞", maxHp: 840, maxMp: 140, attack: 98, defense: 26, speed: 46, isBoss: false,
      lore: "*Your shadow doing something different under the mirrored floor. It decided to come up.*",
      moves: [
        { name: "Under Strike",    emoji: "⬇️", damage: 98, mpCost: 0,  weight: 3 },
        { name: "Different Thing", emoji: "🪞", damage: 78, mpCost: 35, weight: 3, effect: { kind: "bleed", value: 35, duration: 4 } },
        { name: "Return Below",    emoji: "💨", damage: 0,  mpCost: 30, weight: 2, effect: { kind: "regen", value: 65, duration: 2 } },
      ],
    },
    8: { id: "trophy_guardian", name: "Trophy Guardian", emoji: "🏆", maxHp: 900, maxMp: 130, attack: 102, defense: 30, speed: 35, isBoss: false,
      lore: "*Made from the shadows of every warrior whose equipment lines the walls.*",
      moves: [
        { name: "Trophy Blow",   emoji: "🏆", damage: 102, mpCost: 0,  weight: 3 },
        { name: "Shadow Army",   emoji: "⚔️", damage: 82,  mpCost: 45, weight: 3, effect: { kind: "bleed", value: 38, duration: 4 } },
        { name: "Dark Fortress", emoji: "🏰", damage: 0,   mpCost: 50, weight: 2, effect: { kind: "regen", value: 72, duration: 3 } },
        { name: "Execution",     emoji: "💀", damage: 130, mpCost: 65, weight: 1 },
      ],
    },
    9: { id: "shadow_gate_warden", name: "Shadow Gate Warden", emoji: "🚪", maxHp: 960, maxMp: 160, attack: 108, defense: 32, speed: 38, isBoss: false,
      lore: "*The last line of defense before the throne.*",
      moves: [
        { name: "Gate Seal",        emoji: "🚪", damage: 108, mpCost: 0,  weight: 3 },
        { name: "Shadow Judgement", emoji: "⚖️", damage: 88,  mpCost: 50, weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Dark Bastion",     emoji: "🛡️", damage: 0,   mpCost: 55, weight: 2, effect: { kind: "regen", value: 78, duration: 3 } },
        { name: "Final Ward",       emoji: "💥", damage: 142, mpCost: 70, weight: 1 },
      ],
    },
  },
  boss: {
    id: "lord_vael_the_shadow", name: "Lord Vael, the Shadow", emoji: "🌑",
    maxHp: 4800, maxMp: 700, attack: 155, defense: 52, speed: 65, isBoss: true,
    lore: "*He hunted his own shadow. Caught it. Became it. He has your shadow already.*",
    entranceMonologue: [
      `🌑 *Vael stands from the throne before you fully enter.*`,
      `🌑 **Vael:** *"Your shadow arrived ahead of you."*`,
      `🌑 **Vael:** *"It told me everything."*`,
      `🌑 **Vael:** *"Your fears. Your doubt. The moment you considered turning back."*`,
      `🌑 **Vael:** *"I don't particularly want to fight you."*`,
      `🌑 **Vael:** *"But I've been alone in this throne room for a very long time."*`,
      `🌑 **Vael:** *"And your shadow asked me to."*`,
    ],
    deathMonologue: `🌑 *His shadow — the original — dissolves.*\n🌑 **Vael:** *"Tell it I understand."*\n🌑 **Vael:** *"Your shadow is proud of you. In case it doesn't know how to say so."*`,
    playerKillTaunt: `🌑 **Vael:** *"Your shadow is mine now."*\n🌑 **Vael:** *"Welcome to the collection."*`,
    reactToHeavyHit: [
      `🌑 **Vael:** *"Strong. The shadow undersold you."*`,
    ],
    reactToLightHit: [
      `🌑 **Vael:** *"Your shadow knows you're capable of more than that."*`,
    ],
    reactToHeal: [`🌑 **Vael:** *"The shadows feed me. They always have."*`],
    reactToPlayerLow: [
      `🌑 **Vael:** *"Don't give up now. Your shadow came this far with you."*`,
    ],
    reactToBossLow: [
      `🌑 **Vael:** *"...Your shadow was right about you."*`,
      `🌑 **Vael:** *"I think I'm going to lose."*\n🌑 *He doesn't seem upset.*`,
    ],
    midBattleThoughts: [
      `🌑 **Vael:** *"Your shadow told me the void almost broke you. You made it through anyway."*`,
      `🌑 **Vael:** *"I've been in this throne room for centuries. This is the most I've felt in a long time."*`,
    ],
    enrageLines: [
      `🌑 **Vael:** *"I DIDN'T CONQUER MY OWN SHADOW TO LOSE TO YOURS."*`,
      `🌑 **Vael — ENRAGED:** *"THIS DOMINION. IS. MINE."*`,
    ],
    enrageAt: 24,
    moves: [
      { name: "Shadow Execution",  emoji: "🌑", damage: 148, mpCost: 0,  weight: 3, taunt: `🌑 **Vael:** *"Shadow Execution. Your shadow told me where your blind spot is."*` },
      { name: "Umbra Chains",      emoji: "⛓️", damage: 98,  mpCost: 55, weight: 3, effect: { kind: "stun", value: 0, duration: 1 }, taunt: `🌑 **Vael:** *"Umbra Chains."*` },
      { name: "Shadow World",      emoji: "🌍", damage: 115, mpCost: 65, weight: 2, effect: { kind: "slow", value: 38, duration: 3 }, taunt: `🌑 **Vael:** *"Shadow World. My physics now."*` },
      { name: "Vael's Lesson",     emoji: "📖", damage: 132, mpCost: 70, weight: 2, effect: { kind: "bleed", value: 42, duration: 4 }, taunt: `🌑 **Vael:** *"Vael's Lesson. I learned this from your shadow."*` },
      { name: "Shadow Regen",      emoji: "🌑", damage: 0,   mpCost: 55, weight: 1, effect: { kind: "regen", value: 122, duration: 3 }, taunt: `🌑 **Vael:** *"Shadow Regen."*` },
    ],
    enrageMoves: [
      { name: "DOMINION STRIKE",     emoji: "👑", damage: 256, mpCost: 0,  weight: 3, taunt: `🌑 **Vael — ENRAGED:** *"DOMINION STRIKE. THIS DOMINION IS MINE."*` },
      { name: "Shadow Annihilation", emoji: "💥", damage: 204, mpCost: 90, weight: 3, effect: { kind: "bleed", value: 60, duration: 5 }, taunt: `🌑 **Vael — ENRAGED:** *"Shadow Annihilation."*` },
      { name: "Eclipse",             emoji: "🌘", damage: 170, mpCost: 80, weight: 2, effect: { kind: "silence", value: 0, duration: 3 }, taunt: `🌑 **Vael — ENRAGED:** *"Eclipse."*` },
    ],
  },
};
export default arc6;
