// ARC 7: THE CELESTIAL PRISON — Floors 61–70
import type { ArcData } from './types';
const arc7: ArcData = {
  arc: 7, name: "The Celestial Prison", theme: "divine",
  entryNarration: "*Angels hang from the ceiling by their wings — pinned there by light itself. They have no eyes. They are not blind. They see everything.*",
  floorNarrations: {
    61: "*The entry hall. Beautiful beyond description. The beauty makes the wrongness worse.*",
    62: "*Chains everywhere — not metal. Solidified light. Still humming.*",
    63: "*An angel kneels in the corridor, head bowed. It has been waiting for something to pass.*",
    64: "*The cells here. What was imprisoned shattered the doors from inside and left.*",
    65: "*Halfway. Not criminals were kept here. Mistakes. Heaven's experiments gone wrong.*",
    66: "*A great hall filled with thrones, all empty.*",
    67: "*The hymns start here. Coming from everywhere and nowhere.*",
    68: "*The warden's quarters. The warden is gone. The warden's judgment is still here.*",
    69: "*The golden light here is blinding. Literally. You navigate by sound.*",
    70: "*A single cell, larger than all others. The door is open. The occupant is inside anyway.*",
  },
  mobs: {
    61: { id: "eyeless_angel", name: "Eyeless Angel", emoji: "👼", maxHp: 980, maxMp: 160, attack: 112, defense: 32, speed: 45, isBoss: false,
      lore: "*An angel without eyes. It sees more than you.*",
      moves: [
        { name: "Holy Strike",    emoji: "✨", damage: 112, mpCost: 0,  weight: 3 },
        { name: "Sightless Gaze", emoji: "👁️", damage: 88,  mpCost: 40, weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Celestial Hum",  emoji: "🎵", damage: 0,   mpCost: 45, weight: 2, effect: { kind: "regen", value: 75, duration: 3 } },
      ],
    },
    62: { id: "chain_seraph", name: "Chain Seraph", emoji: "⛓️", maxHp: 1020, maxMp: 140, attack: 116, defense: 28, speed: 40, isBoss: false,
      lore: "*Was imprisoned here so long it became the chains.*",
      moves: [
        { name: "Light Chain",   emoji: "⛓️", damage: 116, mpCost: 30, weight: 3, effect: { kind: "slow", value: 35, duration: 4 } },
        { name: "Bind",          emoji: "🔒", damage: 88,  mpCost: 45, weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Heavenly Mend", emoji: "💚", damage: 0,   mpCost: 50, weight: 2, effect: { kind: "regen", value: 82, duration: 3 } },
      ],
    },
    63: { id: "kneeling_watcher", name: "Kneeling Watcher", emoji: "🧎", maxHp: 1060, maxMp: 120, attack: 118, defense: 30, speed: 38, isBoss: false,
      lore: "*It has been kneeling since before you were born. It wasn't worshipping. It was waiting.*",
      moves: [
        { name: "Rising Judgment",  emoji: "⬆️", damage: 118, mpCost: 0,  weight: 4 },
        { name: "Patient Strike",   emoji: "🎯", damage: 95,  mpCost: 35, weight: 3, effect: { kind: "bleed", value: 40, duration: 4 } },
        { name: "Return to Prayer", emoji: "💚", damage: 0,   mpCost: 40, weight: 2, effect: { kind: "regen", value: 78, duration: 3 } },
      ],
    },
    64: { id: "shattered_divine", name: "Shattered Divine", emoji: "💔", maxHp: 1040, maxMp: 150, attack: 120, defense: 22, speed: 52, isBoss: false,
      lore: "*One of heaven's experiments that went wrong enough to be imprisoned.*",
      moves: [
        { name: "Broken Divinity",  emoji: "💔", damage: 120, mpCost: 0,  weight: 3 },
        { name: "Holy Fracture",    emoji: "✨", damage: 98,  mpCost: 40, weight: 3, effect: { kind: "burn", value: 38, duration: 4 } },
        { name: "Desperate Reform", emoji: "🌀", damage: 0,   mpCost: 50, weight: 2, effect: { kind: "regen", value: 85, duration: 3 } },
      ],
    },
    65: { id: "divine_mistake", name: "The Divine Mistake", emoji: "❓", maxHp: 1100, maxMp: 170, attack: 124, defense: 26, speed: 45, isBoss: false,
      lore: "*Heaven created it, looked at what they'd made, and immediately imprisoned it here.*",
      moves: [
        { name: "Confused Wrath", emoji: "❓", damage: 124, mpCost: 0,  weight: 3 },
        { name: "Why Strike",     emoji: "💢", damage: 100, mpCost: 35, weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Self Question",  emoji: "🔁", damage: 0,   mpCost: 45, weight: 2, effect: { kind: "regen", value: 90, duration: 3 } },
      ],
    },
    66: { id: "throne_wraith", name: "Throne Wraith", emoji: "👑", maxHp: 1140, maxMp: 160, attack: 128, defense: 30, speed: 42, isBoss: false,
      lore: "*The spirit of whoever once sat in one of the hall's thrones.*",
      moves: [
        { name: "Throne Strike",  emoji: "👑", damage: 128, mpCost: 0,  weight: 3 },
        { name: "Divine Decree",  emoji: "📜", damage: 105, mpCost: 50, weight: 3, effect: { kind: "silence", value: 0, duration: 2 } },
        { name: "Rule of Heaven", emoji: "⚖️", damage: 0,   mpCost: 55, weight: 2, effect: { kind: "regen", value: 95, duration: 3 } },
      ],
    },
    67: { id: "hymn_construct", name: "Hymn Construct", emoji: "🎵", maxHp: 1160, maxMp: 200, attack: 130, defense: 26, speed: 50, isBoss: false,
      lore: "*Built from the hymns themselves. It is music that decided music wasn't enough.*",
      moves: [
        { name: "Hymn Strike",   emoji: "🎵", damage: 130, mpCost: 30, weight: 3 },
        { name: "Holy Chord",    emoji: "🎶", damage: 108, mpCost: 50, weight: 3, effect: { kind: "slow", value: 40, duration: 4 } },
        { name: "Hymnal Regen",  emoji: "💚", damage: 0,   mpCost: 55, weight: 2, effect: { kind: "regen", value: 100, duration: 3 } },
      ],
    },
    68: { id: "warden_judgment", name: "Warden's Judgment", emoji: "⚖️", maxHp: 1200, maxMp: 180, attack: 135, defense: 32, speed: 44, isBoss: false,
      lore: "*The warden is gone but the judgment remains.*",
      moves: [
        { name: "Verdict Strike",   emoji: "⚖️", damage: 135, mpCost: 0,  weight: 3 },
        { name: "Sentence",         emoji: "📜", damage: 110, mpCost: 55, weight: 3, effect: { kind: "stun", value: 0, duration: 1 } },
        { name: "Law of Heaven",    emoji: "✨", damage: 0,   mpCost: 60, weight: 2, effect: { kind: "regen", value: 105, duration: 3 } },
        { name: "Absolute Verdict", emoji: "💥", damage: 165, mpCost: 75, weight: 1 },
      ],
    },
    69: { id: "blinding_guardian", name: "Blinding Guardian", emoji: "☀️", maxHp: 1280, maxMp: 200, attack: 140, defense: 36, speed: 40, isBoss: false,
      lore: "*Guards the approach with light so pure it's weaponized.*",
      moves: [
        { name: "Blinding Ray",   emoji: "☀️", damage: 140, mpCost: 40, weight: 3, effect: { kind: "slow", value: 45, duration: 4 } },
        { name: "Holy Purge",     emoji: "✨", damage: 118, mpCost: 55, weight: 3, effect: { kind: "burn", value: 42, duration: 5 } },
        { name: "Divine Bastion", emoji: "🛡️", damage: 0,   mpCost: 65, weight: 2, effect: { kind: "regen", value: 112, duration: 3 } },
        { name: "Corona",         emoji: "🌟", damage: 175, mpCost: 80, weight: 1 },
      ],
    },
  },
  boss: {
    id: "archangel_serath", name: "Archangel Serath", emoji: "👼",
    maxHp: 5400, maxMp: 800, attack: 178, defense: 60, speed: 70, isBoss: true,
    lore: "*Imprisoned for knowing too much about heaven itself. She has been waiting. Not for rescue. For someone worthy.*",
    entranceMonologue: [
      `👼 *She is sitting on the floor, wings folded. No throne.*`,
      `👼 *She looks up. She has no eyes.*`,
      `👼 **Serath:** *"You climbed sixty floors to reach me."*`,
      `👼 **Serath:** *"None of them were ready for what comes after me."*`,
      `👼 **Serath:** *"Show me you're worth the next thirty floors."*`,
    ],
    deathMonologue: `👼 *Serath folds her wings.*\n👼 **Serath:** *"Worthy. Finally."*\n👼 **Serath:** *"What comes after me... prepare for it."*\n👼 **Serath:** *"The tower gets honest after this."*`,
    playerKillTaunt: `👼 **Serath:** *"Not yet worthy."*\n👼 **Serath:** *"Return when you are."*`,
    reactToHeavyHit: [
      `👼 **Serath:** *"Your light is dim but it's there. I can see it now."*`,
      `👼 **Serath:** *"Sixty floors and you still have that in you. Remarkable."*`,
    ],
    reactToLightHit: [
      `👼 **Serath:** *"I've waited centuries for a proper fight. Don't waste it."*`,
    ],
    reactToHeal: [`👼 **Serath:** *"Divinity sustains. This is its nature."*`],
    reactToPlayerLow: [
      `👼 **Serath:** *"I can see your soul is strong even when your body isn't. Use that."*`,
    ],
    reactToBossLow: [
      `👼 **Serath:** *"...The light in you. I see it."*`,
      `👼 **Serath:** *"Worthy."*`,
    ],
    midBattleThoughts: [
      `👼 **Serath:** *"I can see your soul from here. It's stronger than you treat it."*`,
      `👼 **Serath:** *"What imprisoned me was truth. What frees you is the same thing."*`,
    ],
    enrageLines: [
      `👼 *The broken wings spread full.*`,
      `👼 **Serath — ENRAGED:** *"I WILL NOT BE DENIED A PROPER FIGHT."*`,
    ],
    enrageAt: 26,
    moves: [
      { name: "Divine Strike",   emoji: "✨", damage: 172, mpCost: 0,  weight: 3, taunt: `👼 **Serath:** *"Divine Strike."*` },
      { name: "Judgment Ray",    emoji: "☀️", damage: 138, mpCost: 60, weight: 3, effect: { kind: "burn", value: 48, duration: 4 }, taunt: `👼 **Serath:** *"Judgment Ray."*` },
      { name: "Sacred Silence",  emoji: "🤫", damage: 90,  mpCost: 70, weight: 2, effect: { kind: "silence", value: 0, duration: 3 }, taunt: `👼 **Serath:** *"Sacred Silence."*` },
      { name: "Seraph Heal",     emoji: "💚", damage: 0,   mpCost: 65, weight: 2, effect: { kind: "regen", value: 132, duration: 3 }, taunt: `👼 **Serath:** *"Seraph Heal."*` },
      { name: "Chain of Heaven", emoji: "⛓️", damage: 200, mpCost: 90, weight: 1, taunt: `👼 **Serath:** *"Chain of Heaven."*` },
    ],
    enrageMoves: [
      { name: "HEAVEN'S WRATH",    emoji: "⚡", damage: 290, mpCost: 0,   weight: 3, taunt: `👼 **Serath — ENRAGED:** *"HEAVEN'S WRATH."*` },
      { name: "Holy Annihilation", emoji: "✨", damage: 232, mpCost: 100, weight: 3, effect: { kind: "burn", value: 72, duration: 5 }, taunt: `👼 **Serath — ENRAGED:** *"Holy Annihilation."*` },
      { name: "Light of Truth",    emoji: "🌟", damage: 180, mpCost: 85,  weight: 2, effect: { kind: "silence", value: 0, duration: 3 }, taunt: `👼 **Serath — ENRAGED:** *"Light of Truth."*` },
    ],
  },
};
export default arc7;
